### ISSUE TITLE
[BUG] "no configuration found"

### ISSUE THREAD

**Issue by piotrvivo** [TheAnsuz/Lethal-Company-Configurable-Company-API#76] opened 2024-10-26 12:04 UTC
## **Describe the bug**
What happened that made you think something does not work as intended. A short description with something like *The menu does not open regardless of how many times I click*.

## **How to reproduce the issue**
Try to explain what you did to reproduce the issue. If you down know what you did ir is unclear, leave it blank. For example *click host, go back and then click again*

## **Mods and profile**
It's very important that you write the version of the game and the version of Configurable Company or any related mods to the issue. Use the following line:
- Game version: v49
- Configurable company: v3.3.0

Profile code: my_profile_code

## **Extra information**
Anything else you want to add. If you have console logs, any error or screenshot, this is the ideal place, otehrwise, you can just leave it empty.

**Comment by TheAnsuz** [comment] 2024-10-26 12:10
Hello @piotrvivo 

Do you mind providing information about your issue?

**Comment by TheAnsuz** [comment] 2024-10-28 16:05
Hello @piotrvivo 

I will close the issue due to lack of information.

The only related things that I can think of are:
- No configurations in the menu: this is caused by not having [lethal company variables](https://thunderstore.io/c/lethal-company/p/AMRV/LethalCompanyVariables/) installed (Configurable company is an API and LCV is the implementation)
- Console logs about scraps not having configurations: you can ignore these if you encounter all scraps in the menu, sometimes is due to dummy items that are not removed by developers and is just LCV picking up on them

If you have other related issues feel free to reopen the issue with more information, thanks in advance!

**Closed as completed by TheAnsuz** 2024-10-28 16:05 UTC
Labels: bug
