### ISSUE TITLE
[Conflict] continue #29, now won't spawn any vanilla creature after install starlancer moonpack

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#34] opened 2024-05-24 21:22 UTC
https://github.com/AudioKnight/Starlancer/issues/33

**Comment by TheAnsuz** [comment] 2024-05-24 23:12
Hello @CoolLKKPS !

This is known issue caused by some custom moons registering enemies with a 0 spawn change, overriding the "default" value that LCV uses and forcing it to 0, you should be able to work around this issue by creating a config file without the issuer mod and then loading it.

There is a work in progress fix but it will likely take some time to fix.

**Comment by TheAnsuz** [comment] 2024-07-19 20:23
Hello @CoolLKKPS 

After A LOT of time, I finally had time to check the issue, should be fixed with the next release.

Thank you in advance!

**Closed as completed by TheAnsuz** 2024-07-19 20:23 UTC
Labels: bug
