### ISSUE TITLE
[QUESTION] Items changing when loading existing save file

### ISSUE THREAD

**Issue by Schmumschmenz** [TheAnsuz/Lethal-Company-Configurable-Company-API#27] opened 2024-05-02 12:19 UTC
Hello,

I have a question regarding an Issue that has accured while loading a config to a save,
usually I change one or two enemy spwanrates and then make a loadout and save it before starting a new game... 

but whenever I have to restart the game or just quit out of the savefile, the configs dont seem to stay applied to that save, because of that I need to load the loudout that I created again, the problem Is that after that the Item IDs or something seems to change causing them to be swapped out... this Is obviously very annoying and sometimes It even prevents the company form firing you effectively softlocking you and forcing you to make a new save...

my Question is how do I avoid any of this? am I missing something, I read the wiki but I dont see any solutions on there.

Thanks In advance.

**Comment by TheAnsuz** [comment] 2024-05-02 12:55
Hello @Schmumschmenz 

I might not have understood your question correctly, you are having issues regarding some configurations not saving their values because their ID's are changing?

ID's should be a static value and should never change, if this is not the case I would need to know what is the configuration that is causing the issue.

Among other things, I understand that you go to the file slot in-game, modify the settings, click save and then you play as usual, is this correct?

Thank you in advance!

**Comment by Schmumschmenz** [comment] 2024-05-04 15:42
yes, I try to elaborate It more:

I Opened the configs menu and then made a loudlout where I changed the spawnrates of butlers and girls on every moon, then before we play I always select the loadout, click on save config, and start the game.

everything always works just fine but as soon as I have to close the lobby due to someone crashing and/or having issues because of an Ingame Bug caused by someother mod, this Is when I go back to the menu and I reselect the loudout and save It again just like I did the first time,

 but then suddently the Items spawn into specifc different ones, for example the shovels always turn Into lockpicker devices for some reason, and the other Items like walkies or flashlights also have the same Item that they get swapped out with... this Is an Issue I only have whenever I want to reload an already existing savefile, thats why I have to completely evoid closing the lobby at all because I have no Idea whats the reason thats causing this weird "bug" and Its especially frustrating when something like a knife or a shotgun gets changed...

**Comment by TheAnsuz** [comment] 2024-05-04 19:37
Hello @Schmumschmenz 

To clarify, you don't need to save and load presets everytime, once you make changes on your config you can click **save** and they will remain forever (configs are different on each save file). You can also check what values are modified or not saved as they will appear in *italic if not saved* and **bold if they are not the default values**. 

About the issue with the items, LCV will not modify anything related to items or their IDs, I will gladly check the issue but it might be related to the crash itself or it might be caused by other mod.

Feel free to share your profile code and configurations so I can check the issue myself!

**Comment by TheAnsuz** [comment] 2024-05-25 23:47
Hello @Schmumschmenz 

I will be closing the issue as there has been no updates or information.

Feel free to reopen the issue if you need.

**Closed as completed by TheAnsuz** 2024-05-25 23:47 UTC
Labels: question
