### ISSUE TITLE
[Issue] Error on start

### ISSUE THREAD

**Issue by CoolLKKPS** [TheAnsuz/Lethal-Company-Configurable-Company-API#6] opened 2024-04-06 06:45 UTC
![image](https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/assets/96377775/138a337c-4321-44eb-8e2a-e4fce7c127c7)

so here's the logs, pretty sure that's bc i disabled levelloader in the game

[06:39:17.6060795] [Info : BepInEx] Loading [Configurable Company Variables 2.0.0]
[06:39:17.9126683] [Warning: HarmonyX] AccessTools.GetTypesFromAssembly: assembly Lethal_Company_Variables, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
at System.Reflection.Assembly.GetTypes () [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000
at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_000D
System.TypeLoadException: Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[06:39:18.1387508] [Error : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LCV.Utils.InitiateAttribute.InitiateAll () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/Utils/InitiateAttribute.cs:33)
LCV.LCVPlugin.Awake () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/LCVPlugin.cs:36)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[06:39:18.1387508] [Error : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'LCV.Compat.LethalLevelLoaderCompat:Levels' (1) due to: Could not load file or assembly 'LethalLevelLoader, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
LCV.Utils.InitiateAttribute.InitiateAll () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/Utils/InitiateAttribute.cs:33)
LCV.LCVPlugin.Awake () (at D:/Programacion/Visual Studio/Lethal Company Variables/LCV/LCVPlugin.cs:36)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by CoolLKKPS** [comment] 2024-04-06 09:18
v50 issues not only this, also new traps and new creature **might** won't be affect

**Comment by TheAnsuz** [comment] 2024-04-06 10:30
Hello @CoolLKKPS.

About the v50 stuff, It will be added upon **full release**, as it's most likely to be changed.

For the other part of the issue, I will upload a fix ASAP.

**Comment by CoolLKKPS** [comment] 2024-04-06 10:58
recall some false issues, so v50 new traps and new creature still working actually

**Comment by TheAnsuz** [comment] 2024-04-06 12:02
Hi @CoolLKKPS 

The issue is fixed with the latest patch (2.0.2)

I will proceed to close the issue, if it still happens feel free to reopen it and I will make an in-depth search.

Thanks for the report

**Closed as completed by TheAnsuz** 2024-04-06 12:02 UTC
Labels: bug
